### ISSUE TITLE
error: 'predecessors' following the 'template' keyword does not refer to a template

### ISSUE THREAD

**Issue by sjackman** [GATB/bcalm#54]
Bcalm 2.2.1 fails to build with clang on macOS 10.15.
```
In file included from /tmp/bcalm-20200120-5545-zrb02j/build/ext/gatb-core/src/gatb/template/TemplateSpecialization5.cpp.in_128.cpp:5:
1373
/tmp/bcalm-20200120-5545-zrb02j/gatb-core/gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp:155:58: error: 'predecessors' following the 'template' keyword does not refer to a template
1374
        GraphVector<Node> predecessors = graph->template predecessors (node);
1375
                                                         ^
1376
```
See https://github.com/brewsci/homebrew-bio/pull/870/checks?check_run_id=399734948#step:3:1373
and https://github.com/brewsci/homebrew-bio/pull/870

**Comment by rchikhi** [comment]
thanks for the report! I don't own a Mac. Any idea what's a simple fix here?

**Comment by sjackman** [comment]
I suspect (but haven't tried) that you could reproduce this error with `clang` on Linux.

**Comment by rchikhi** [comment]
Worth a try !
```
(base) [rayan@blok-bok bcalm]$ mkdir buildclang
(base) [rayan@blok-bok bcalm]$ cd buildclang
(base) [rayan@blok-bok buildclang]$ export CC=/usr/bin/clang
(base) [rayan@blok-bok buildclang]$ export CXX=/usr/bin/clang++
(base) [rayan@blok-bok buildclang]$  cmake .. && make -j8
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
[..]
6 warnings generated.
6 warnings generated.
[100%] Linking CXX executable bcalm
[100%] Built target bcalm
```

"unfortunately" it works with clang 9.0.0 on Linux

**Comment by sjackman** [comment]
Do you have CI set up for this repository? I'm really liking GitHub Actions for CI. It has both Linux and macOS runners.

**Comment by rchikhi** [comment]
yes in fact there's Travis that generates Mac binaries every release. Good to know about Github Actions!

**Comment by sjackman** [comment]
The error is from this line
```
GraphVector<Node> predecessors = graph->template predecessors (node);
```
`error: 'predecessors' following the 'template' keyword does not refer to a template`

In the current `gatb-core` that line removes the `template` word:
```
        GraphVector<Node> predecessors = graph->predecessors (node);
```
https://github.com/GATB/gatb-core/blob/1dc23ffdba8e53b6f8b13973f3e74b519fb7b5d1/gatb-core/src/gatb/debruijn/impl/BranchingAlgorithm.cpp#L155

I have no idea which one it _should_ be.

**Comment by rchikhi** [comment]
ha thanks for the investigation! according to https://github.com/GATB/gatb-core/issues/28#issuecomment-497351218 it should be the latter! so problem should go away in next release

**Comment by sjackman** [comment]
Glad to hear it. Thanks, Rayan!
